name: Minify Workflow
on:
  push:
    branches: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1

      # Auto-commit to repository
       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@v4.2.5
         with:
          branch: gh-pages # The branch the action should deploy to.
          folder: . # The folder the action should deploy.